---
title: "Equifinality-3 Post-Training/Tuning Analysis"
author: "Mark E. Madsen"
date: "October 30, 2014"
output:
  pdf_document:
    number_sections: true
    toc: true
    toc_depth: 2
    latex_engine: xelatex
    keep_tex: true
mainfont: Minion Pro
monofont: Bitstream Vera Sans Mono
mathfont: Minion Math
sansfont: ITC Legacy Sans Std Medium
fontsize: 11pt
bibliography: ../../paper/madsen2015-ctmixtures.bib
csl-style: american-antiquity.csl
---

```{r, echo=FALSE, results='asis', warning=FALSE, message=FALSE}
library(dplyr)
# produce pandoc tables and output from R objects
library(pander)
library(knitr)
library(ggplot2)
library(caret)
# The following imports helper methods for random forests and data set splits
library(mmadsenr)
# load data frame, results in object "eq3_pop_df" in the workspace
base_dir <- "~/local-research/diss/experiments/experiment-ctmixtures"
image_file <- get_data_path(basedir = base_dir, suffix = "equifinality-3", filename = "classification-caret-results.RData")
load(image_file)
```

# ROC Analysis #

```{r roc-comparison, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
# calculate ROC curves for each of the data sets
roc_pop <- calculate_roc_binary_classifier(fit = training_fit, 
                                           test = eq3_pop_test, 
                                           label_class = "two_class_label", 
                                           curve_title="Population Census Data")
roc_sampled <- calculate_roc_binary_classifier(fit = sampled_training_fit, 
                                               test = eq3_sampled_test_20, 
                                               label_class = "two_class_label", 
                                               curve_title="Sampled Data")

plot_multiple_roc(roc_pop, roc_sampled)

```




